site_name: AIRR-Formats
repo_url: https://github.com/airr-community/airr-formats
theme: mkdocs
markdown_extensions:
  - def_list
  - sane_lists
  - smarty
  - toc:
      permalink: True
docs_dir: 'docs'
pages:
  - 'About': index.md
  - 'Data Standards':
    - 'Formats Overview': common.md
    - 'Alignment Data': alignments.md
    - 'Rearrangement Data': rearrangements.md
